<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SectionItemSeeder extends Seeder
{
    public function run(): void
    {
        $sectionItems = [
            [
                'id' => 1,
                'section_key' => 'why_led_events',
                'component_type' => 'why_block',
                'group_title' => 'Why LED EVENTS',
                'page' => 'home',
                'title_en' => 'System',
                'title_km' => 'ប្រព័ន្ធ',
                'description_en' => 'Lorem ipsum dolor sit amet...',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:44:54'),
                'updated_at' => Carbon::parse('2026-04-20 09:44:54'),
            ],
            [
                'id' => 2,
                'section_key' => 'why_led_events',
                'component_type' => 'why_block',
                'group_title' => 'Why LED EVENTS',
                'page' => 'home',
                'title_en' => 'Reliability',
                'title_km' => 'ភាពជឿជាក់',
                'description_en' => 'Lorem ipsum dolor sit amet...',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 2,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:44:54'),
                'updated_at' => Carbon::parse('2026-04-20 09:44:54'),
            ],
            [
                'id' => 3,
                'section_key' => 'why_led_events',
                'component_type' => 'why_block',
                'group_title' => 'Why LED EVENTS',
                'page' => 'home',
                'title_en' => 'Experience',
                'title_km' => 'បទពិសោធន៍',
                'description_en' => 'Lorem ipsum dolor sit amet...',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 3,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:44:54'),
                'updated_at' => Carbon::parse('2026-04-20 09:44:54'),
            ],
            [
                'id' => 4,
                'section_key' => 'services',
                'component_type' => 'service_card',
                'group_title' => 'Our Services',
                'page' => 'home',
                'title_en' => 'LED Screen Rental',
                'title_km' => 'ជួលអេក្រង់ LED',
                'description_en' => 'We provide high-resolution LED screen rental in Cambodia for indoor and outdoor events.',
                'description_km' => 'យើងផ្តល់សេវាជួលអេក្រង់ LED គុណភាពខ្ពស់សម្រាប់កម្មវិធីក្នុង និងក្រៅអគារ',
                'image' => null,
                'icon' => null,
                'link' => '/services/led-screen-rental',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:49:48'),
                'updated_at' => Carbon::parse('2026-04-20 09:49:48'),
            ],
            [
                'id' => 5,
                'section_key' => 'services',
                'component_type' => 'service_card',
                'group_title' => 'Our Services',
                'page' => 'home',
                'title_en' => 'Stage Rental',
                'title_km' => 'ជួលឆាក',
                'description_en' => 'Our stage rental services include professional stage setup for events of all sizes.',
                'description_km' => 'សេវាជួលឆាករបស់យើងមានការរៀបចំឆាកវិជ្ជាជីវៈសម្រាប់កម្មវិធីគ្រប់ប្រភេទ',
                'image' => null,
                'icon' => null,
                'link' => '/services/stage-rental',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 2,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:49:48'),
                'updated_at' => Carbon::parse('2026-04-20 09:49:48'),
            ],
            [
                'id' => 6,
                'section_key' => 'services',
                'component_type' => 'service_card',
                'group_title' => 'Our Services',
                'page' => 'home',
                'title_en' => 'Sound System',
                'title_km' => 'ប្រព័ន្ធសំឡេង',
                'description_en' => 'We offer professional sound system rental in Phnom Penh with high-quality audio equipment.',
                'description_km' => 'យើងផ្តល់សេវាជួលប្រព័ន្ធសំឡេងគុណភាពខ្ពស់នៅភ្នំពេញ',
                'image' => null,
                'icon' => null,
                'link' => '/services/sound-system',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 3,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:49:48'),
                'updated_at' => Carbon::parse('2026-04-20 09:49:48'),
            ],
            [
                'id' => 7,
                'section_key' => 'services',
                'component_type' => 'service_card',
                'group_title' => 'Our Services',
                'page' => 'home',
                'title_en' => 'Lighting Production',
                'title_km' => 'ផលិតកម្មភ្លើង',
                'description_en' => 'We provide professional lighting production services for indoor and outdoor events in Cambodia.',
                'description_km' => 'យើងផ្តល់សេវាផលិតកម្មភ្លើងវិជ្ជាជីវៈសម្រាប់កម្មវិធីក្នុង និងក្រៅអគារ',
                'image' => null,
                'icon' => null,
                'link' => '/services/lighting-production',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 4,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:55:02'),
                'updated_at' => Carbon::parse('2026-04-20 09:55:02'),
            ],
            [
                'id' => 8,
                'section_key' => 'services',
                'component_type' => 'service_card',
                'group_title' => 'Our Services',
                'page' => 'home',
                'title_en' => 'Full Event Production',
                'title_km' => 'ផលិតកម្មព្រឹត្តិការណ៍ពេញលេញ',
                'description_en' => 'We provide complete event production solutions including LED, stage, sound, and lighting.',
                'description_km' => 'យើងផ្តល់ដំណោះស្រាយផលិតកម្មព្រឹត្តិការណ៍ពេញលេញ រួមមាន LED ឆាក សំឡេង និងភ្លើង',
                'image' => null,
                'icon' => null,
                'link' => '/services/full-event-production',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 5,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:55:13'),
                'updated_at' => Carbon::parse('2026-04-20 09:55:13'),
            ],
            [
                'id' => 9,
                'section_key' => 'why_us',
                'component_type' => 'why_card',
                'group_title' => 'Why Us',
                'page' => 'why card',
                'title_en' => 'System',
                'title_km' => 'ប្រព័ន្ធ',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'description_km' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:57:36'),
                'updated_at' => Carbon::parse('2026-04-20 09:57:36'),
            ],
            [
                'id' => 10,
                'section_key' => 'why_us',
                'component_type' => 'why_card',
                'group_title' => 'Why Us',
                'page' => 'why card',
                'title_en' => 'Backup',
                'title_km' => 'បម្រុងទុក',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'description_km' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 2,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:57:36'),
                'updated_at' => Carbon::parse('2026-04-20 09:57:36'),
            ],
            [
                'id' => 11,
                'section_key' => 'why_us',
                'component_type' => 'why_card',
                'group_title' => 'Why Us',
                'page' => 'why card',
                'title_en' => 'Team',
                'title_km' => 'ក្រុមការងារ',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'description_km' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 3,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:57:36'),
                'updated_at' => Carbon::parse('2026-04-20 09:57:36'),
            ],
            [
                'id' => 12,
                'section_key' => 'why_us',
                'component_type' => 'why_card',
                'group_title' => 'Why Us',
                'page' => 'why card',
                'title_en' => 'Execution',
                'title_km' => 'ការអនុវត្ត',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'description_km' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 4,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:57:36'),
                'updated_at' => Carbon::parse('2026-04-20 09:57:36'),
            ],
            [
                'id' => 13,
                'section_key' => 'why_us',
                'component_type' => 'why_card',
                'group_title' => 'Why Us',
                'page' => 'why card',
                'title_en' => 'Experience',
                'title_km' => 'បទពិសោធន៍',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'description_km' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 5,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 09:57:36'),
                'updated_at' => Carbon::parse('2026-04-20 09:57:36'),
            ],
            [
                'id' => 14,
                'section_key' => 'media',
                'component_type' => 'media_intro',
                'group_title' => 'Event Videos',
                'page' => 'media',
                'title_en' => 'Event Videos',
                'title_km' => 'វីដេអូព្រឹត្តិការណ៍',
                'description_en' => 'We provide high-resolution LED screen rental in Cambodia for indoor and outdoor events.',
                'description_km' => 'យើងផ្តល់សេវាជួលអេក្រង់ LED គុណភាពខ្ពស់សម្រាប់កម្មវិធីក្នុង និងក្រៅអគារ',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:06:16'),
                'updated_at' => Carbon::parse('2026-04-20 10:06:16'),
            ],
            [
                'id' => 15,
                'section_key' => 'media',
                'component_type' => 'media_video',
                'group_title' => 'Event Videos',
                'page' => 'media',
                'title_en' => 'Events Video 1',
                'title_km' => 'វីដេអូ 1',
                'description_en' => 'We provide high-resolution LED screen rental in Cambodia for indoor and outdoor events.',
                'description_km' => 'យើងផ្តល់សេវាជួលអេក្រង់ LED',
                'image' => null,
                'icon' => null,
                'link' => '/media/video-1',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:06:58'),
                'updated_at' => Carbon::parse('2026-04-20 10:06:58'),
            ],
            [
                'id' => 16,
                'section_key' => 'media',
                'component_type' => 'media_video',
                'group_title' => 'Event Videos',
                'page' => 'media',
                'title_en' => 'Events Video 2',
                'title_km' => 'វីដេអូ 2',
                'description_en' => 'Our stage rental services include professional stage setup for events of all sizes',
                'description_km' => 'សេវាជួលឆាកវិជ្ជាជីវៈ',
                'image' => null,
                'icon' => null,
                'link' => '/media/video-2',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 2,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:09:41'),
                'updated_at' => Carbon::parse('2026-04-20 10:09:41'),
            ],
            [
                'id' => 17,
                'section_key' => 'media',
                'component_type' => 'media_video',
                'group_title' => 'Event Videos',
                'page' => 'media',
                'title_en' => 'Events Video 3',
                'title_km' => 'វីដេអូ 3',
                'description_en' => 'We offer professional sound system rental in Phnom Penh with high-quality audio equipment to ensure clear sound',
                'description_km' => 'សេវាជួលប្រព័ន្ធសំឡេងគុណភាពខ្ពស់',
                'image' => null,
                'icon' => null,
                'link' => '/media/video-3',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 3,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:09:52'),
                'updated_at' => Carbon::parse('2026-04-20 10:09:52'),
            ],
            [
                'id' => 18,
                'section_key' => 'media',
                'component_type' => 'media_gallery',
                'group_title' => 'Behind the Scenes',
                'page' => 'media',
                'title_en' => 'Behind the Scenes',
                'title_km' => 'នៅពីក្រោយឆាក',
                'description_en' => 'Lorem 3',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => 'behind-scenes-1.jpg',
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:11:10'),
                'updated_at' => Carbon::parse('2026-04-20 10:11:10'),
            ],
            [
                'id' => 19,
                'section_key' => 'blog',
                'component_type' => 'blog_post',
                'group_title' => null,
                'page' => 'blog',
                'title_en' => 'Article 01',
                'title_km' => 'អត្ថបទ 01',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => 'https://www.loremledevent.com/article-01',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:40:32'),
                'updated_at' => Carbon::parse('2026-04-22 21:23:10'),
            ],
            [
                'id' => 20,
                'section_key' => 'blog',
                'component_type' => 'blog_post',
                'group_title' => 'Articles',
                'page' => 'blog',
                'title_en' => 'Article 02',
                'title_km' => 'អត្ថបទ 02',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit...',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => 'https://www.loremledevent.com/article-02',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 2,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:41:34'),
                'updated_at' => Carbon::parse('2026-04-20 10:41:34'),
            ],
            [
                'id' => 21,
                'section_key' => 'blog',
                'component_type' => 'blog_post',
                'group_title' => 'Projects',
                'page' => 'blog',
                'title_en' => 'Project 03',
                'title_km' => 'គម្រោង 03',
                'description_en' => 'Lorem ipsum dolor sit amet...',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => 'https://www.loremledevent.com/project-03',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 3,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:41:46'),
                'updated_at' => Carbon::parse('2026-04-20 10:41:46'),
            ],
            [
                'id' => 22,
                'section_key' => 'blog',
                'component_type' => 'blog_post',
                'group_title' => 'Projects',
                'page' => 'blog',
                'title_en' => 'Project 04',
                'title_km' => 'គម្រោង 04',
                'description_en' => 'Lorem ipsum dolor sit amet...',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => 'https://www.loremledevent.com/project-04',
                'button_text_en' => 'Read More',
                'button_text_km' => 'អានបន្ថែម',
                'sort_order' => 4,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:42:01'),
                'updated_at' => Carbon::parse('2026-04-20 10:42:01'),
            ],
            [
                'id' => 23,
                'section_key' => 'how_we_work',
                'component_type' => 'work_step',
                'group_title' => 'How We Work',
                'page' => 'home',
                'title_en' => '01',
                'title_km' => '០១',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 1,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:51:00'),
                'updated_at' => Carbon::parse('2026-04-20 10:51:00'),
            ],
            [
                'id' => 24,
                'section_key' => 'how_we_work',
                'component_type' => 'work_step',
                'group_title' => 'How We Work',
                'page' => 'home',
                'title_en' => '02',
                'title_km' => '០២',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 2,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:51:00'),
                'updated_at' => Carbon::parse('2026-04-20 10:51:00'),
            ],
            [
                'id' => 25,
                'section_key' => 'how_we_work',
                'component_type' => 'work_step',
                'group_title' => 'How We Work',
                'page' => 'home',
                'title_en' => '03',
                'title_km' => '០ៃ',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 3,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:51:00'),
                'updated_at' => Carbon::parse('2026-04-20 10:51:00'),
            ],
            [
                'id' => 26,
                'section_key' => 'how_we_work',
                'component_type' => 'work_step',
                'group_title' => 'How We Work',
                'page' => 'home',
                'title_en' => '04',
                'title_km' => '០៤',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 4,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:51:00'),
                'updated_at' => Carbon::parse('2026-04-20 10:51:00'),
            ],
            [
                'id' => 27,
                'section_key' => 'how_we_work',
                'component_type' => 'work_step',
                'group_title' => 'How We Work',
                'page' => 'home',
                'title_en' => '05',
                'title_km' => '០៥',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 5,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:51:00'),
                'updated_at' => Carbon::parse('2026-04-20 10:51:00'),
            ],
            [
                'id' => 28,
                'section_key' => 'how_we_work',
                'component_type' => 'work_step',
                'group_title' => 'How We Work',
                'page' => 'home',
                'title_en' => '06',
                'title_km' => '០៦',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
                'description_km' => 'Lorem ipsum dolor sit amet...',
                'image' => null,
                'icon' => null,
                'link' => null,
                'button_text_en' => null,
                'button_text_km' => null,
                'sort_order' => 6,
                'is_active' => 1,
                'type' => null,
                'meta' => null,
                'created_at' => Carbon::parse('2026-04-20 10:51:00'),
                'updated_at' => Carbon::parse('2026-04-20 10:51:00'),
            ],
        ];

        // Disable foreign key constraints temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Clear existing data if needed
        DB::table('section_items')->truncate();

        // Insert the data
        foreach ($sectionItems as $item) {
            DB::table('section_items')->insert($item);
        }

        // Re-enable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
